slothy-optimizer/slothy

examples/naive/aarch64/X25519-AArch64-simple.s

Previously the script in [scripts/nelight_x25519.sh](https://github.com/slothy-optimizer/slothy/blob/f4051970fc89bea7b1cf4bc9dba4eac6983a8dfb/scripts/nelight_x25519.sh) would fail with to the following parsing error:
`ERROR:root:Failed to parse instruction add    x4, sp, STACK_SCALAR`, where `STACK_SCALAR` is defined via `#define STACK_SCALAR  112` in [examples/naive/aarch64/X25519-AArch64-simple.s](https://github.com/slothy-optimizer/slothy/blob/f4051970fc89bea7b1cf4bc9dba4eac6983a8dfb/examples/naive/aarch64/X25519-AArch64-simple.s). 
The reason for the error is most likely a typo: [There](https://github.com/slothy-optimizer/slothy/blob/f4051970fc89bea7b1cf4bc9dba4eac6983a8dfb/examples/naive/aarch64/X25519-AArch64-simple.s#L1473C8-L1473C8) is a `#` missing before the `STACK_SCALAR`, …

Add missing `#` before immediate

---

examples/naive/aarch64/X25519-AArch64-simple.s
paper/clean/neon/X25519-AArch64-simple.s
paper/scripts/slothy_x25519.sh
slothy/core/config.py
slothy/core/core.py
slothy/core/heuristics.py
slothy/targets/aarch64/aarch64_neon.py
slothy/targets/arm_v81m/arch_v81m.py

* Reduce number of steps in X25519 optimization script
* Circumvent issue in address offset fixup by marking address-register of `ld2` as input-output and thereby bypassing fixup mechanism

Fix x25519 example and improve efficiency

---

paper/scripts/slothy_dilithium_ntt_a55.sh
paper/scripts/slothy_dilithium_ntt_a72.sh
paper/scripts/slothy_fft.sh
paper/scripts/slothy_kyber_ntt_a55.sh
paper/scripts/slothy_kyber_ntt_a72.sh
paper/scripts/slothy_ntt_helium.py
paper/scripts/slothy_sqmag.sh
paper/scripts/slothy_x25519.sh
slothy/core/config.py
slothy/core/core.py
slothy/core/slothy.py
slothy/helper.py
slothy/targets/aarch64/aarch64_neon.py
slothy/targets/aarch64/cortex_a55.py
slothy/targets/aarch64/cortex_a72_frontend.py
slothy/targets/arm_v81m/arch_v81m.py
slothy/targets/arm_v81m/cortex_m55r1.py
slothy/targets/arm_v81m/cortex_m85r1.py

When optimizing for Cortex-M55, Cortex-M85, Cortex-A55 or Cortex-A72, the option `-c with_llvm_mca` will run LLVM MCA (Machine Code Analyzer) on the original and optimized source code and emit the estimated performance characteristics as comments in the generated source file.
This is useful to get an indicator of the quality of the performance improvements even without dedicated hardware.
To test, build llvm from source, https://github.com/llvm/llvm-project (you need a very recent version since `llvm-mca` was only added to the default build in Nov'23) and make sure `llvm-mca` is in your `PATH`.
`-c with_llvm_mca` can be passed to the various scripts in `paper/` via `SLOTHY_FLAGS="-c with_llvm_mca"`.
NOTE, though, that the LLVM MCA scheduling models are approximative as well. Moreover, …

Add config option for adding LLVM MCA based performance statistics

---

slothy/core/config.py
slothy/targets/aarch64/aarch64_neon.py

This PR introduces the config option `reserved_regs_are_locked`. When set (default), it means that reserved registers are treated as locked, that is, existing uses will not be renamed. When unset, existing used of reserved registers may (in fact, will) be renamed.
More details in `config.py`.
Fixes: #49

Make the renaming of reserved registers configurable

---

slothy/targets/aarch64/aarch64_neon.py
slothy/targets/aarch64/cortex_a55.py
slothy/targets/aarch64/neoverse_n1_experimental.py

This adds support for a few arithmetic instructions in AArch64.
The updated uarchs are Neoverse N1 and Cortex A55.

Add support for vmull2, ngc xzr sbcs xzrs, sbcs xzrs and cmn

---

slothy/core/core.py

v9.5 is quite old by now and not likely to be used by many anymore, esp. with `requirements.txt` pointing at v9.7. Moreover, the lexicographic version comparison does not work for v9.10 anymore.

Remove OR-Tools version check

---

requirements.txt
slothy/core/core.py

`is_low` and `is_high` are only meaningful in SW pipelining mode. Calling them in straightline mode introduces wrong assertions which have led to the x25519 script failing.
Thanks for Amin for noticing.

Fix bug in cross-loop dependency handling

---

.gitignore
slothy/helper.py

The GNU as [1] allows macro definitons and invoation to separate arguments by spaces or commas. So far SLOTHY cannot handle spaces in both definitions and invocations.
This commit adds that functionality.
Here is some minimal examples for which SLOTHY currently fails:
```asm
.macro mx aa bb cc
add \aa, \bb, \cc
.endm
.macro my aa, bb, cc
add \aa, \bb, \cc
.endm
start:
mx x3, x1, x2
mx x4  x1  x2
my x5, x1, x2
my x6  x1  x2
end:
```
The following SLOTHY calls can be used to test:
```py
import logging
import sys
from slothy import Slothy
import slothy.targets.aarch64.aarch64_neon as AArch64_Neon
import slothy.targets.aarch64.cortex_a55 as Target_CortexA55
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
arch = AArch64_Neon
target = Target_CortexA55
slothy = Slothy(arch, target) …
```

Allow spaces instead of commas in macro definitions and invocations

---

slothy/core/config.py

`config.constraints.functional_only` is a wrapper property around `model_latencies` and `model_functional_units`. However, previously it would only be supported to set `functional_only = True`, in which case both `model_latencies` and `model_functional_units` would be set to `False` -- attempting `functional_only = False`, in turn, would be silently ignored, which is certainly not desired.
This commit modifies the `functional_only` setter to always set both `model_functional_units` and `model_latencies` to the negation of the value that's being specified.

Allow setting `functional_only = False`

---

slothy/helper.py

We use fixed-width comments to align `// gap` annotations and the `// ...` position-visualization. With the previous behaviour of `SourceLine._strip_comments()`, the right-padding of the `gap` comment would be removed, leading to misaligned output.
This commit modifies comment trimming to use lstrip() only.

Don't trim comments to the right

---

slothy/core/config.py

The visualize_expected_performance option introduced in https://github.com/slothy-optimizer/slothy/commit/d2fcecad5a313a59de585b3f4350902536f71028, allows to switch from the `// gap` output, to a visualization of the performance (see examples below). 
I think the visualization is strictly better and should be enabled by default. 
What do you think @hanno-becker and @dop-amin?
gap output: 
```
// Instructions:    20
// Expected cycles: 28
// Expected IPC:    0.71
//
// Cycle bound:     28.0
// IPC bound:       0.71
//
// Wall time:     0.18s
// User time:     0.18s
//
// ----- original position ----->
// 0                        25
// |------------------------|----
ldr q4, [x1, #0]                        // *.............................
// gap                                  // …
```

Change default of visualize_expected_performance to True

---

slothy/core/core.py
slothy/core/heuristics.py

Use via `config.constraints.minimize_register_usage = {REGISTER_TYPE}`, e.g. `config.constraints.minimize_register_usage=AArch64_Neon.RegisterType.GPR`.

Fix `minimize_register_usage` objective

---

slothy/targets/aarch64/aarch64_neon.py
slothy/targets/aarch64/neoverse_n1_experimental.py

This patch adds `umull_wform` (`pattern = "umull <Xd>, <Wa>, <Wb>"`) to the N1 cost model, and defines more variants of simple integer ops.

Add umull to the N1 cost model and define more variants of simple integer ops

---

slothy/core/config.py
slothy/core/core.py
slothy/core/heuristics.py
slothy/targets/aarch64/aarch64_neon.py

SLOTHY has long supported assembly which uses symbolic register names instead of architectural ones. This commit improves the compatibility of this feature with both (a) complex workloads using numerous symbolic registers, and (b) architectures offering only a small register file, by adding experimental support for a simplified form of register spilling.

Extend support for symbolic assembly via spilling

---

slothy/core/config.py
slothy/core/core.py

Sometimes one already knows a lower bound for an objective (spills, stalls) and searching longer is a waste of compute. 
This PR adds an option to SLOTHY to provide that lower bound at which SLOTHY stops optimizing.
Usage example (for spill code generation): 
```
slothy.config.objective_lower_bound = 7
slothy.config.inputs_are_outputs = True
slothy.config.constraints.functional_only = True
slothy.config.constraints.allow_spills = True
slothy.config.constraints.minimize_spills = True
slothy.config.constraints.allow_reordering = False
slothy.optimize(start="layer1234_start", end="layer1234_end")
```
It also fixes a small error in core.py line 3259 that lead to the following error: 
```
Traceback (most recent call last):
File "/home/mjk/git/pqmx/slothy/example.py", line 2405, in <module> …
```

Add config obective_lower_bound

---

slothy/core/core.py

Right now we are exporting the CP-SAT model after _solve() has returned.
However, at the end of _solve(), we add the found solution as hints to the model such that sub-sequent solving of the same model (with a different objective) run faster.
This resulted in the exported model not being the one that was being solved originally.
This commit moves the export.

Move export of CP-SAT model

---

example.py
examples/naive/aarch64/aarch64_loop_subs.s
examples/naive/loop_le.s
slothy/core/slothy.py
slothy/helper.py
slothy/targets/aarch64/aarch64_neon.py
slothy/targets/arm_v81m/arch_v81m.py
slothy/targets/common.py

This PR adds a more generic strucutre to deal with loops: Subclasses of Loop implement a specific type of loop, for exmaple having a certain sequence of instructions at the end. The extraction works the same and is thus implemented in `Loop`, while the methods to produce the code differ. 
I am open to suggestions for how to improve this approach; for my usecases wrt. armv7m it worked fine like this.

More general structure for loop parsing

---

slothy/targets/arm_v7m/arch_v7m.py
slothy/targets/arm_v7m/cortex_m7.py

Small tweaks to the Armv7E-M model: 
- Add `smlatb` and `ldrb` with postincrement (and corresponding uArch model for M7)
- make barrel shift parsing more flexibile (can now write either `asr#1` or `asr #1` (before it was limited to the latter)

Extend Armv7E-M architecture model

---

.github/actions/setup-ubuntu/action.yml
.github/workflows/test_basic.yaml
example.py
examples/naive/aarch64/ntt_kyber_123_4567.s
examples/naive/armv7m/armv7m_simple0_func.s
requirements.txt
slothy/core/config.py
slothy/core/core.py
slothy/core/slothy.py
slothy/helper.py
slothy/targets/aarch64/aarch64_neon.py
slothy/targets/arm_v7m/arch_v7m.py
slothy/targets/arm_v81m/arch_v81m.py

By default, SLOTHY includes a 'selfcheck' verifying that the DFGs
of input and output are isomorphic with respect to the rescheduling
found by SLOTHY. This selfcheck is very powerful and should catch most
modelling errors in SLOTHY.
However, some aspects of SLOTHY remain outside of the scope of the
DFG-based selfcheck:
- Address offset fixup
This is a historically rather error prone feature to which the self-check
is blind (since it relies on making the DFG blind to address increments).
- Loop boundaries
If SW pipelining is enabled, the selfcheck checks equivalence of a
_bounded unrolling_ of the input and output loops.
Therefore, it would not catch issues with (a) the loop boundary, or
(b) exceptional iterations for low loop counts.
While it is not SLOTHY's goal to provide formal …

Add equivalence tester

---

slothy/helper.py

I'm getting the following warnings with Python3.12: 
```
/home/mjk/git/slothy/slothy/helper.py:778: SyntaxWarning: invalid escape sequence '\('
l = re.sub(f"\\\\{arg}\\\\\(\)", val, l)
/home/mjk/git/slothy/slothy/helper.py:819: SyntaxWarning: invalid escape sequence '\s'
macro_regexp_txt += '(,|\s)'.join(arg_regexps)
```
This commit fixes the escaping.

fix Python3.12 reg ex warnings

---

slothy/core/core.py
slothy/core/slothy.py
slothy/helper.py

Without stderr from `llvm-mc`, it's difficult to debug the issue. This commit modifies the call to `llvm-mc` so that the error output is printed is an exception is thrown while running `llvm-mc`.

selftest: Print stderr output upon llvm-mc failure

---

example.py
examples/naive/aarch64/aarch64_split0.s
examples/opt/aarch64/aarch64_split0_opt_a55.s
slothy/core/dataflow.py
slothy/core/slothy.py
slothy/targets/aarch64/aarch64_neon.py

Extracted from #61 as introduced via d1a075f75b78c05671b012b5730d066a06935f7e.

Use Fusion CB for splitting

---

slothy/targets/arm_v7m/arch_v7m.py

Some small fixes pulled out of the `armv7m` branch:
1) Setting the arch_name
2) Fixing the model for vldm/vstm. #116 changed the model for those and incorrectly modelled it as allowing any combination of registers in the register list of vldm/vstm. While this is true for ldm and stm, it doesn't work for vldm/vstm. There it actually need to be a list of consecutive registers (which makes sense because otherwise there are just too many combinations). This lead to an explosion of combinations and, consequently, RAM usage. 
3) Work around LLVM complaining about `.w` for ldr/str instructions with negative offset. These are 32-bit anyway as only the 32-bit encoding allows negative offsets. We cannot fix this in our input code as the address fixup changes the offests. Better ideas are welcome! …

Fix armv7m arch model

---

slothy/core/config.py
slothy/core/core.py
slothy/core/dataflow.py
slothy/core/slothy.py
slothy/helper.py

We encountered further issues with the selftest in the `armv7m` branch. This PR refines it further
1) When unicorn fails to run code, currently this fails silently and the selftest continues to run failing in the assertions checking the output resulting in misleading error messages. This is changed now to fail immediately with an appropriate eror message. 
2) The configuration option `selftest_address_gprs` was misnamed as addresses can also be contained in non-gpr-registers. I renamed it to `selftest_address_registers`
3) Previously the selftest would determine which registers are supposed to contain addresses  (and allocate memory
accordingly) by going through all memory operations and assuming that address registers used in those are the
inputs holding the addresses initially.
This …

Refine selftest further

---

example.py
examples/naive/armv7m/loop_vmov_cmp_forced.s
examples/opt/armv7m/loop_vmov_cmp_forced_opt_m7.s
slothy/core/slothy.py
slothy/helper.py

* Helps in case of ambigous loop types and makes the operation more predictable.

Allow to force loop type

---

slothy/targets/aarch64/aarch64_neon.py

When both early and late instructions are used, the loop counter needs adjusting by 2. A recent change broke this because of an unfortunate type confusion leading to the computation of `2 * '1' == '11'` rather than `2 * 1 == 2`.
This commit fixes the computation of the loop counter adjustment.

Fix counter correction for SW pipelining with early + late insts

---

slothy/core/core.py

Noticed this was still broken on `main` while re-optimizing 769 Dilithium NTT.

Fix typo in pretty-printing of orig<->opt permutation

---

slothy/core/config.py
slothy/core/core.py
slothy/core/dataflow.py
slothy/targets/aarch64/aarch64_neon.py

Commits extracted from `armv7m` branch as the example for the 769 Dilithium NTT breaks without this.

Extend Spilling 

---

examples/naive/armv7m/keccakf1600_adomnicai_m7.s
examples/opt/armv7m/keccakf1600_adomnicai_m7_opt_m7.s

Functions with `.global` that get not renamed caused conflicts while building. 
These functions do not get called externally so there is no need for it to be there.

Avoid function name collisions for Keccak

---

slothy/core/core.py

In examples where we need to use the `before=my_id` tag together with the splitting heuristic, the optimization would fail because the instruction tagged with `my_id` is not guranteed to appear within the "window" the heuristic is considering at some point. However, in this situation, the constraint can just be omitted as there is no risk of the instructions being placed in an "illegal" way, based on the `before` tag anyways.

Locked ordering: Allow id find to fail with splitting

---

requirements.txt

This PR updates the unicorn engine to version 2.1.2.
This releases fixes a compatibility problem with Apple Silicon macOS that prevented SLOTHY
running on macOS.

Update to unicorn 2.1.2 to fix compatibility with macOS

---

examples/opt/aarch64/aarch64_loop_subs_opt_a55.s
slothy/targets/aarch64/aarch64_neon.py

This PR addresses the issue #165. In the `SubsLoop` class, the wrong parameter was used in the writer of loop. 
The parameters `lbl_start`, `lbl_end` are some legacy carry-over from the Armv8-M models. I feel like we could remove them globally at some point as they do not add too much value in my opinion. 
* Resolves #165

Fix aarch64 loop labels being overwritten

---

README.md

Fixes #173 
Document that Python 3.11 is required now.
Document need to adjust PATH to include slothy-cli and LLVM tools.

Update README for Python 3.11

---

.github/dependabot.yml
requirements.txt
slothy/core/dataflow.py
slothy/core/heuristics.py
slothy/core/slothy.py

Resolves #186 
Depends on #185.
According to https://github.com/jsh9/pydoclint/issues/213 it was a bug that pydoclint expected AssertionErrors to be listed in the raises section of the docstrings. 
With pydoclint 0.6.5 that was reverted and you _cannot_ have AssertionErrors in the docstrings. Unfortunately that means that linting will fail iwht pydoclint >= 0.6.1 and < 0.6.5....

Update pydoclint to 0.6.5 and resolve warnings 

---

slothy/targets/arm_v81m/arch_v81m.py

This change fixes a bug with `vldr_gather` where registers are not renamed correctly. The bug is caused by `vldr_gather.write()` tracking old data from parse-time, rather than updated registers from renaming.
Fixes #202

Only reference API-relevant args in `vldr_gather.write()`

---

examples/naive/aarch64/aarch64_simple0.s
slothy/targets/aarch64/aarch64_neon.py

* Resolves #201 
Previously, a whitespace before/after a separating token such as ',' inside an instruction pattern would be interpreted as mandatory, leading to parsing failures for valid instructions strings such as 'ldr q0,[x0]'.
This commit fixes this by allowing any amount of whitespaces before/after tokens such as ',', '.', '[', ']', regardless of the number of spaces in the instruction pattern.

AArch64: Don't enforce whitespacing before/after separating tokens

---

slothy/targets/aarch64/aarch64_neon.py

* Based on #212 
Found during some joint debugging with @nebeid

AArch64: Relax spacing around immediates, add some shifted logical instructions

---

examples/naive/armv8m/crt/_example.py
examples/naive/armv8m/dilithium/_example.py
examples/naive/armv8m/kyber/_example.py
examples/naive/armv8m/ntt_256/_example.py
paper/scripts/slothy_ntt_helium.py
slothy/core/config.py
slothy/core/dataflow.py
tests/naive/armv8m/_test.py

- Solves #235 
Since we introduced typing annotations for symbolic register, e.g., r<tmp> and refactor the MVE model to follow the same approach as for AArch64, we should entirely remove the typing hints from the SLOTHY configuration and all examples.

Remove typing hints configuration option

---

slothy/targets/arm_v7m/arch_v7m.py

ldrd_imm uses a pre_index. However, it contains no write method that updates the immediate in case the address offset fixup modified the pre_index. This commit adds the missing write function.
This likely does not have any impact on the examples we have, as for the Cortex-M7, we commonly used the splitting to split an ldrd into two ldrs.

Armv7-M: Fix ldrd_imm

---

slothy/targets/arm_v81m/arch_v81m.py
tests/naive/armv8m/_test.py
tests/naive/armv8m/instructions.s

- Implements modeling of r13 as a GPR with sp alias
- Resolves https://github.com/slothy-optimizer/slothy/issues/238

Armv8.1-M: Allow use of sp/r13

---

slothy/targets/aarch64/neoverse_n1_experimental.py

This adds Ldp_Q (immediate offset or post-increment) to the Neoverse N1 model. From the [SWOG](https://developer.arm.com/documentation/109896/latest/) (page 33):
- latency 7
- throughput 1
- used pipelines: L and I (However, we simplify this to only L as for the other instructions).
Resolves https://github.com/slothy-optimizer/slothy/issues/265

Add Ldp_Q to Neoverse N1 model

---

slothy/targets/aarch64/aarch64_neon.py
tests/naive/aarch64/instructions.s

Adds the following parser definitions and corresponding tests in instructions.s
vumull{2}_lane
vsmull{2}_lane
vumlal{2}_lane
vsmlal{2}_lane
vumlsl{2} (vector)
vsmlsl{2} (vector)
vumlsl{2}_lane
vsmlsl{2}_lane
I put the last four instructions (vumlsl{2}, vsmlsl{2}, vumlsl{2}_lane, vumlsl{2}_lane ) into the class Vml"a"l. The reason is:
Major micro-architecture references (ARM SWOG docs and Apple core micro-benchmarks) indicate that these ops share the same execution and forwarding behaviour as existing Vmlal family members.
ARM SWOG A72 (p25) ARM SWOG A76 (p26) ARM SWOG A55 (p35) group the instructions umlal{2}, smlal{2}, umlsl{2}, smlsl{2} into "ASIMD Multiply Accumulate Long" instruction groups
The websites
https://dougallj.github.io/applecpu/firestorm-simd.html …

Add multiply long instructions neon 

---

slothy/targets/aarch64/aarch64_neon.py

Also, add pseudo-instruction AESDR for fused AESD+AESIMC, analogous to the pseudi-instruction AESR for AESE+AESMC.
* Fixes https://github.com/slothy-optimizer/slothy/issues/278

Add AESD, AESIMC instructions to AArch64 model

---

slothy/targets/aarch64/aarch64_neon.py
slothy/targets/aarch64/cortex_a55.py
slothy/targets/aarch64/cortex_a72_frontend.py
slothy/targets/aarch64/neoverse_n1_experimental.py
tests/naive/aarch64/instructions.s

AArch64: add `s` register support and add `fmov` and `uaddlv` instructions

---

slothy/cli/__init__.py

Check if output directory exists and is writable before beginning SLOTHY optimization to prevent wasting time on invalid output paths.
Fixes https://github.com/slothy-optimizer/slothy/issues/63

slothy-cli: validate output directory before starting optimization

---

slothy/targets/aarch64/aarch64_neon.py
slothy/targets/arm_v7m/arch_v7m.py
slothy/targets/arm_v81m/arch_v81m.py
tests/naive/aarch64/instructions.s
tests/naive/armv8m/instructions.s

- Resolves #284 
- This commit suppoting immediate values without `#`
- Following model are supported:
- `aarch64`
- `arch_v7m`
- `arch_v81m`
1. The `imm_pattern` was updated to recognize immediate values regardless of the presence of `#`, and the `<imm>` prefix strip off logic was adjusted accordingly.
2. Additionally, commas `,` were removed from `imm_pattern` to avoid misinterpreting operands like `q2, UXTW 2` as a single immediate:
```
.syntax unified
start:
vstrw.32 q0, [r0, #16]
vstrw.u32 q0, [r0, q2, UXTW 2].
end:
```
3. To support symbolic aliases like `#(SHIFT)`, used in instructions such as follow, we now combine the old symbolic-style and the new numeric literal patterns. This allows both formats to be parsed properly.
```
vrshr.s32 q0, q1, #(SHIFT)
```

Feat: Supporting immediate values without #

---

slothy/core/slothy.py

In `helper.py`, an `AsmHelperException` is raised if `__str__()` is called on a `SourceLine` object. I found (at least) this one case, where the optimization of a WIP example failed due to a `SourceLine` being used inside an f-string. Fixed by using `to_string()` from `SourceLine`.

Don't use str(line)

---

slothy/core/config.py
slothy/core/core.py

Resolves https://github.com/slothy-optimizer/slothy/issues/296

Fix: Do not create model dir if log_model is not set

---

slothy/core/dataflow.py
tests/naive/armv8m/_test.py
tests/naive/armv8m/tag_test.s

- Resolves: #305
- This PR fixes the warning message shown when using the `// @slothy:ignore_useless_output` annotation.
- Previously, the message incorrectly stated "Ignoring this as requested by \`config.allow_useless_instructions\`!" even when the `// @slothy:ignore_useless_output` annotation was used.
- It now correctly displays: "Ignoring this as requested by \`// @slothy:ignore_useless_output\` annotation!".

Fix: correct the warning message phrased for // @slothy:ignore_useless_output

---

slothy/targets/aarch64/aarch64_neon.py
slothy/targets/aarch64/cortex_a55.py
slothy/targets/aarch64/cortex_a72_frontend.py
tests/naive/aarch64/instructions.s

this pr adds the `eon` instruction to `aarch64` architecture and to the `a55`, `a72`, `neoverse N1` micro architectures. 
Note for `a72` I import the superset `AArch64Logical` instead of just `eon`, which includes all other logical instructions. And for N1 nothing had to be done, as it already imports `AArch64Logical`.

AArch64: Add eon instruction

---

slothy/targets/aarch64/aarch64_neon.py

- Resolves: #219
- Add support for using repeated `.<dt>` in instruction patterns, while keeping backward compatibility.
- This PR solve problem by:
- Introducing a new static method `_replace_duplicate_mnemonicKey()` in `AArch64Instruction` to handle duplicate `<dt>` specifiers during parsing and writing.
- Enforcing that all `.<dt*>` are equal during parsing.
- Here is an example:
- For pattern: `smlsl <Vd>.<dt0>, <Va>.<dt1>, <Vb>.<dt1>`
- When parsing:
- `smlsl v6.4s, v7.4h, v8.4h` -> Passed,
- `smlsl v6.4s, v7.4h, v8.4s` -> Failed,
return `return "Inconsistent dataname: <dt0> vs <dt1> for datatype: 4s"`
- `smlsl v6.4s, v7.4h, v8.16b` -> Failed,
return `"Inconsistent datatype: 4h vs 16b for dataname: <dt1>"`

AArch64: Add support for repeated .<dt> specifiers
